name: Reproduce Setup-Java Rate limit for Graalvm

on:
  workflow_dispatch:

jobs:
  reproduce-hang:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        run: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30] # 10 parallel runs
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java (Graalvm 17)
        uses: actions/setup-java@v5
        with:
          java-version: 24-ea   # leaving patch unspecified forces API lookup
          distribution: graalvm

      - name: Confirm Java version
        run: java -version
