
name: Test Graalvm rate limit

on:
  workflow_dispatch:

jobs:
  test-graalvm:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest",'macos-latest']
        version:
          - "11"
          - "21.0.4+8.1"
          - "24-ea"
    steps:
      - uses: actions/checkout@v4
      - uses: mahabaleshwars/setup-java@fix/graalvm-api-rate-limit
        with:
          distribution: 'graalvm'
          java-version: ${{ matrix.version }}
      - name: Validate Java Version
        run: java -version
  
  test-graalvm-arch:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest","macos-latest"]
        version:
          - "11"
          - "21.0.4+8.1"
          - "24-ea"
    steps:
      - uses: actions/checkout@v4
      - uses: mahabaleshwars/setup-java@fix/graalvm-api-rate-limit
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}
      - name: Validate Java Version
        run: java -version

  test-explicit-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (explicit token)
        uses: mahabaleshwars/setup-java@fix/graalvm-api-rate-limit
        with:
          distribution: temurin
          java-version: 17
          token: ${{ secrets.GITHUB_TOKEN }} # Uses provided input, not environment fallback

      - name: Verify Java
        run: java -version

  test-env-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove input, use implicit GITHUB_TOKEN
        uses: mahabaleshwars/setup-java@fix/graalvm-api-rate-limit
        with:
          distribution: graalvm
          java-version: '17.0.12'
        # No 'token' input provided

      - name: Verify Java
        run: java -version

  test-no-token:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }} # disables the default GITHUB_TOKEN for simulation
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (no token input or environment)
        uses: mahabaleshwars/setup-java@fix/graalvm-api-rate-limit
        with:
          distribution: temurin
          java-version: 11
        # No token input, environment variable unset

      - name: Verify Java
        run: java -version

  test-invalid-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (invalid token)
        uses: mahabaleshwars/setup-java@fix/graalvm-api-rate-limit
        with:
          distribution: temurin
          java-version: 17
          token: "this_is_not_a_valid_token"

      - name: Verify Java
        run: java -version

  test-pat-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java using PAT
        uses: mahabaleshwars/setup-java@fix/graalvm-api-rate-limit
        with:
          distribution: temurin
          java-version: 21
          token: ${{ secrets.PAT }}

      - name: Verify Java
        run: java -version

  test-explicit-token_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (explicit token)
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          token: ${{ secrets.GITHUB_TOKEN }} # Uses provided input, not environment fallback

      - name: Verify Java
        run: java -version

  test-env-token_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove input, use implicit GITHUB_TOKEN
        uses: actions/setup-java@v5
        with:
          distribution: graalvm
          java-version: '24-ea'
        # No 'token' input provided

      - name: Verify Java
        run: java -version

  test-no-token_main:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }} # disables the default GITHUB_TOKEN for simulation
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (no token input or environment)
        uses: actions/setup-java@v5
        with:
          distribution: sapmachine
          java-version: '17.0.7'
        # No token input, environment variable unset

      - name: Verify Java
        run: java -version

  test-invalid-token_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (invalid token)
        uses: actions/setup-java@v5
        with:
          distribution: oracle
          java-version: '21.0.4'
          token: "this_is_not_a_valid_token"

      - name: Verify Java
        run: java -version

  test-pat-token_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java using PAT
        uses: actions/setup-java@v5
        with:
          distribution: jetbrains
          java-version: '11.0.11'
          token: ${{ secrets.PAT }}

      - name: Verify Java
        run: java -version
